version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ctf_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ctf_user
      POSTGRES_PASSWORD: ctf_pass
      POSTGRES_DB: ctf_db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ctf_user -d ctf_db"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - ctf_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ctf_backend
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    networks:
      - ctf_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 3s
      retries: 10

  # Optional: pgAdmin (DB GUI)
  # Uncomment to enable
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: ctf_pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   networks:
  #     - ctf_net

volumes:
  db_data:

networks:
  ctf_net:
    driver: bridge
