name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Make your token available to all steps (no login step needed)
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Railway CLI (binary)
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      # Optional sanity check: shows who the CLI is authenticated as
      - name: Railway whoami
        run: railway whoami || true

      # Deploy directly — project/env come from railway.json
      - name: Deploy to Railway
        run: railway up --service ae8a39df-6af1-44c5-a12e-15efed38aff8 --ci
