name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Railway CLI
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      # Deploy using the token; target your service by name or ID
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # If your repo isn't linked automatically in Railway,
          # uncomment the next line and set the project ID as a secret:
          # railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}

          # Use your service name as shown in Railway (or the service ID)
          railway up --service "CTF-Backend"
