name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Make the token available to all steps
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Railway CLI (binary)
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      # Tell the CLI which project to target
      - name: Link project
        run: railway link --project 643efe96-25d9-41cc-9f06-812b34fe9a5a
       

      # Deploy your service (use the service ID to avoid name typos)
      - name: Deploy to Railway
        run: railway up --service ae8a39df-6af1-44c5-a12e-15efed38aff8 --ci
       