name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Railway CLI (binary)
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      #  Authenticate the CLI in CI (non-interactive)
      - name: Railway login (non-interactive)
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --token "$RAILWAY_TOKEN"

      # 📎 Point the CLI at your project (ID from your URL)
      - name: Link project
        run: railway link --project 643efe96-25d9-41cc-9f06-812b34fe9a5a

      # 🚀 Deploy to your service (ID from your URL)
      - name: Deploy to Railway
        run: railway up --service ae8a39df-6af1-44c5-a12e-15efed38aff8 --ci
